### ISSUE TITLE
Epoch time is not strict UTC-based

### ISSUE THREAD

**Issue by brettveenstra** [jdemeuse1204/Jot#1]
UnixDateServices._unixEpoch calls ToLocalTime which is unnecessary and prevents JWT clients from universally analyzing any of the time components of the claim without also knowing what locality the token was created in

**Comment by jdemeuse1204** [comment]
Thank you @brettveenstra, I am looking into this right now.

**Comment by brettveenstra** [comment]
I've forked this and actively working on a solution... basically you have a UnixTimeProvider need (timestamps) and (for testability) a TimeProvider that resolves the current UTC datetime...

**Comment by jdemeuse1204** [comment]
This is fixed in 1.0.1
