### ISSUE TITLE
iat does not use nbf for validation comparison

### ISSUE THREAD

**Issue by brettveenstra** [jdemeuse1204/Jot#5]
When validating a token, a `CreatedTimeCheckFailed` can be returned when a Token is evaluated and the current time is *before* the `iat` value.  This can happen in a webfarm scenario with clock drift.  JWT spec provides for this using `nbf` claim.  Looking at the implementation for `iat` validation though, it only compares current clocks Unix time.  Suggest that if `nbf` claim exists, that is used as first level comparison (returning `true` when the `iat` value occurs after the `nbf`) and then compare as before.

**Comment by jdemeuse1204** [comment]
@brettveenstra Thank you for submitting this issue.  Is there any way you can use custom claim verification or skip the `iat` claim?  Essentially what you would do is this:

#### Custom Verification
```
validationContainer.AddCustomClaimVerification("iat", (claimValue) => 
  {
    return /*Your IAT Verification Here*/;
  });
```

Or you can also skip the `iat` claim like so:

#### Skip
```
validationContainer.SkipClaimVerification(JotDefaultClaims.IAT);
```

Do any of these options help you?  I see what you are saying, but technically this is an invalid token from the CPU that is trying to verify it.

The readme has full examples

**Comment by brettveenstra** [comment]
@jdemeuse1204 - ok, I understand the workaround here... are you certain that you haven't added to the [JWT spec](https://tools.ietf.org/html/rfc7519)?  My take on it is that only `nbf`, when provided, should be validated (like you're doing now), but that `iat` never has date validation...

```

4.1.5.  "nbf" (Not Before) Claim

   The "nbf" (not before) claim identifies the time before which the JWT
   MUST NOT be accepted for processing.  The processing of the "nbf"
   claim requires that the current date/time MUST be after or equal to
   the not-before date/time listed in the "nbf" claim.  Implementers MAY
   provide for some small leeway, usually no more than a few minutes, to
   account for clock skew.  Its value MUST be a number containing a
   NumericDate value.  Use of this claim is OPTIONAL.

4.1.6.  "iat" (Issued At) Claim

   The "iat" (issued at) claim identifies the time at which the JWT was
   issued.  This claim can be used to determine the age of the JWT.  Its
   value MUST be a number containing a NumericDate value.  Use of this
   claim is OPTIONAL.

```

**Comment by jdemeuse1204** [comment]
@brettveenstra  I see what you are saying, I am going to change the verification and do a check to make sure the `iat` is numeric if provided.

**Comment by jdemeuse1204** [comment]
Fixed by PR https://github.com/jdemeuse1204/Jot/pull/6
